---
google:
  url: http://translate.google.co.jp/

excite:
  url: http://www.excite.co.jp/world/english/

infoseek:
  url: http://translation.infoseek.co.jp/

yahoo:
  url: http://honyaku.yahoo.co.jp/


